config/routes.rb
Rails.application.routes.draw do
  resources :users

  resource :session

  resources :subs

  resources :posts do
    resources :comments, only: [:new, :create, :show]
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :author_id, :post_id, :content, presence: true

    belongs_to :author,
      primary_key: :id,
      foreign_key: :author_id,
      class_name: :User

    belongs_to :post

    belongs_to :parent,
      primary_key: :id,
      foreign_key: :parent_id,
      class_name: :Comment

    has_many :children,
      primary_key: :id,
      foreign_key: :parent_id,
      class_name: :Comment

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :url, :title, :content, :author_id, presence: true
  validates :url, :title, uniqueness: true
  validate :sub_exists

  # belongs_to :sub,
  #   primary_key: :id,
  #   foreign_key: :sub_id,
  #   class_name: :Sub

  has_many :comments

  has_many :post_subs

  has_many :subs,
    through: :post_subs,
    source: :sub

  belongs_to :author,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :User


  def sub_exists
    unless PostSub.where(post_id: self.id).count > 0
      errors.add(errors: "sub doesnt exist")
    end
  end


end

app/models/post_sub.rb
class PostSub < ActiveRecord::Base
  validates :post_id, uniqueness: { scope: :sub_id }
  validates :post_id, :sub_id, presence: true

  belongs_to :post

  belongs_to :sub
end

app/models/sub.rb
class Sub < ActiveRecord::Base
  validates :title, :description, :mod_id, presence: true
  validates :title, uniqueness: true

  belongs_to :mod,
    primary_key: :id,
    foreign_key: :mod_id,
    class_name: :User

  has_many :post_subs

  has_many :posts,
    through: :post_subs,
    source: :post

  # has_many :posts,
  #   foreign_key: :sub_id,
  #   primary_key: :id,
  #   class_name: :Post


end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password
  after_initialize :ensure_session_token
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil?: true}

  has_many :posts,
    foreign_key: :author_id,
    primary_key: :id,
    class_name: "Post"

  has_many :subs,
    foreign_key: :mod_id,
    primary_key: :id,
    class_name: :Sub

  has_many :comments,
    primary_key: :id,
    foreign_key: :author_id,
    class_name: :Comment

  def ensure_session_token
    self.session_token ||= SecureRandom::urlsafe_base64(32)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.find_by_credentials(username, password)
    maybe_user = User.find_by(username: username)
    if maybe_user.nil?
      return nil
    end
    if maybe_user.is_password?(password)
      maybe_user
    else
      nil
    end
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(32)
    self.save
    self.session_token
  end

end

app/models/vote.rb
class Vote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def current_user
    User.find_by(session_token: session[:session_token])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @comment = Comment.new()
    if params[:comment][":parent_id"]
      @parent_id = params[:comment][":parent_id"].to_i
    else
      @parent_id = nil
    end
  end

  def show
    @comment = Comment.find_by_id(params[:id])
  end


  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to post_url(@comment.post)
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:author_id, :post_id, :parent_id, :content)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post = Post.new
    render :new
  end

  def create
    fail
    @post = Post.new(post_params)
    if @post.save
      @post.sub_ids = post_params[:sub_ids]
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new
    end
  end

  def destroy
    @post = Post.find_by_id(params[:id])
    @post.delete
    redirect_to posts_url
  end

  def edit
    @post = Post.find_by_id(params[:id])
  end

  def update
    @post = Post.find_by_id(params[:id])
    if @post.update!(post_params.reject {|k,v| k == "sub_ids" })
      @post.sub_ids = post_params[:sub_ids].map(&:to_i)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @posts.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find_by_id(params[:id])
  end

  private

  def post_params
    params.require(:post).permit(:url, :title, :content, :author_id, :sub_ids => [])
  end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def index
    render :index
  end

  def new
    render :new
  end

  def create
    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors] = ["Invalid credentials"]
      render :new
    end
  end

  def destroy
    @user = current_user
    logout
    redirect_to users_url
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/subs_controller.rb
class SubsController < ApplicationController
  def index
    @subs = Sub.all
  end

  def new
    @sub = Sub.new
    render :new
  end

  def create
    @sub = Sub.new(sub_params)
    if @sub.save
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :new
    end
  end

  def show
    @sub = Sub.find_by_id(params[:id].to_i)
    render :show
  end

  def edit
    @sub = Sub.find_by_id(params[:id].to_i)
    render :edit
  end

  def update
    @sub = Sub.find_by_id(params[:id].to_i)
    if @sub.update(sub_params)
      redirect_to sub_url(@sub)
    else
      flash.now[:errors] = @sub.errors.full_messages
      render :edit
    end
  end

  def destroy
    @sub = Sub.find_by_id(params[:id])
    if @sub.delete
      redirect_to subs_url
    else
      render :show
    end
  end

  private

  def sub_params
    params.require(:sub).permit(:title, :description, :mod_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    render :index
  end

  def new
    render :new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to users_url
    else
      flash.now[:errors ] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subs_helper.rb
module SubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<form action=" <%= post_comments_url %>" method="post">
  <%= @parent_id %>

  <input type="hidden" name="authenticity_token" value="form_authenticity_token">
  <input type="hidden" name="comment[author_id]" value=" <%= current_user.id %>">
  <input type="hidden" name="comment[post_id]" value=" <%= params[:post_id] %>">
  <input type="hidden" name="comment[parent_id]" value=" <%= @parent_id %>">
  <input type="text" name="comment[content]" value="">
  <input type="submit" value="Submit Your Awesome Comment this is a long button title">
</form>

app/views/comments/show.html.erb
Comment by <%= @comment.author.username %>
<%= @comment.content %>
<form action=" <%= new_post_comment_url  %>" method="get">
  <input type="hidden" name="comment[:parent_id]" value= "<%=@comment.id%>" >
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="Submit" value="Add a comment to this comment">
</form>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditClone</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <form class="" action="/session" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="_method" value="delete">
    <input type="submit" value="Logout">
  </form>

<%= yield %>

<label for="errors">Errors:
  <%= flash[:errors] %>
</label>

</body>
</html>

app/views/posts/_form.html.erb
<input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>" >
  <label>
    URL:
    <input type="text" name="post[url]" placeholder="URL" value=" <%= @post.url %>">
  </label>
  <label>
    Title:
    <input type="text" name="post[title]" placeholder="Title" value=" <%= @post.title %>">
  </label>
  <label>
    Content:
    <textarea name="post[content]"> <%= @post.content %></textarea>
  </label>
  <label>
    Subs:
    <% Sub.all.each do |one_sub| %>
      <input type="checkbox" name="post[sub_ids][]" value="<%= one_sub.id %>" <%= "checked" if @post.sub_ids.include?(one_sub.id) %>> <%= one_sub.title %>
    <% end %>
  </label>
  <label>
    <input type="hidden" name="post[author_id]" value="<%= current_user.id %>">
  </label>

  <input type="Submit" value="Submit">
</form>

app/views/posts/edit.html.erb
<form action=" <%= post_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
<%= render "form" %>

app/views/posts/new.html.erb
<form action="<%= posts_url %>" method="POST">

<%= render "form" %>

app/views/posts/show.html.erb
<h1> <%= @post.title %></h1>

<p>
<%= @post.content %>
</p>

<% @post.comments.each do |comment| %>
  <%= comment.author.username %> <br>
  <%= comment.content %>

<% end %>

<%= link_to "Add a new comment to this page", new_post_comment_url(@post) %>

app/views/subs/_form.html.erb
  <input type="hidden" name="authenticity_token" value=" <%= form_authenticity_token %>">
  <label>Title:
    <input type="text" name="sub[title]" value=" <%= @sub.title %>">
  </label>

  <label>Description:
    <input type="text" name="sub[description]" value=" <%= @sub.description %>">
  </label>

  <label>
    <input type="hidden" name="sub[mod_id]" value=" <%= current_user.id %>">
  </label>

  <input type="submit">
</form>

app/views/subs/edit.html.erb
<form action=" <%= sub_url %>" method="post">
  <input type="hidden" name="_method" value="patch">
  <%= render "form" %>

app/views/subs/index.html.erb
<ul>
<% @subs.each do |sub| %>
<li> <%= link_to sub.title, sub_url(sub) %> </li>
<% end %>
</ul>

app/views/subs/new.html.erb
<form action=" <%= subs_url %>" method="post">
<%= render "form" %>

app/views/subs/show.html.erb
Title:
<%= @sub.title %>
Description:
<%= @sub.description %>
Moderated By:
<%= @sub.mod_id %>
<ol>
<% @sub.posts.each do |post| %>
<li>
<%= link_to post.title, post_url(post) %>
</li>
<% end %>
</ol>

app/views/users/_form.html.erb
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <% if :url == "edit_url" %>
    <input type="hidden" name="_method" value="patch">
  <% end %>
  <label>
    <input type="text" name="user[username]" placeholder="Username">
  </label>
  <label>
    <input type="password" name="user[password]" placeholder="Password">
  </label>
  <input type="Submit" value="Submit">

</form>

app/views/users/index.html.erb
Hi

<% User.all.each do |user| %>
  <p><%= "#{user.username} ... Logged In" if user == current_user %></p>
<% end %>

app/views/users/new.html.erb
<form class="" action="<%= users_url %>" method="post">
<%= render "form", url: "users_url" %>